name: new test workflow
on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: testing this step
        run: echo "Ran successfully"
      
      - name: testing failed step
        run: |
          exit 0
          echo "failed"

      - name: testing another step
        run: echo "Ran successfully"

